### ISSUE TITLE
advise to support Automatic expansion

### ISSUE THREAD

**Issue by Nyx2022** [adrianbrad/queue#15]
in init the var,i can use queue.WithCapacity to limit the size of new queue,but i wanna the queue can auto expand,so ican pass a small initial count to init the var ,and it will auto expand when i offer some elems rather than return an error,so can you add this option and feature,thank you!

**Comment by adrianbrad** [comment]
Hello @Nyx2022,

If you omit the `WithCapacity` option, the queue will be configured to expand dynamically. You can create such queues using `queue.NewBlocking(elems)`, which does not enforce a specific capacity limit.
